name: "Hello Deploy!"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      Notes_Api_Test: "Notes.Api.Test/Notes.Api.Test.csproj"

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Restore Tests"
        run: dotnet restore $Notes_Api_Test

      - name: "Build Tests"
        run: dotnet build --no-restore --configuration Release $Notes_Api_Test

      - name: "Run Tests"
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --verbosity normal \
            --logger trx \
            $Notes_Api_Test

      - name: "Report Tests"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-report
          path: Notes.Api.Test/TestResults/*.trx
          reporter: dotnet-trx

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      Notes_Api: "Notes.Api/Notes.Api.csproj"

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Restore Application"
        run: dotnet restore $Notes_Api

      - name: "Build Application"
        run: dotnet build --no-restore --configuration Release $Notes_Api

      - name: "Publish Application"
        run: |
          dotnet publish \
            --no-build \
            --configuration Release \
            --output ${{env.DOTNET_ROOT}}/published \
            $Notes_Api

      - name: "Upload Application Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: sticky-notes
          path: ${{env.DOTNET_ROOT}}/published

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: "Download Application Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: sticky-notes

      - name: "Deploy Application to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tae-devops-101-prod'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .